FROM golang:1.19 as base

WORKDIR /app
COPY go.mod go.sum ./

ARG AZDO_ACCESS_TOKEN
RUN echo "machine dev.azure.com login pat password ${AZDO_ACCESS_TOKEN}" > ~/.netrc

RUN go mod download

COPY . .

RUN go build -o ./out/can ./cmd/

FROM alpine:3 as runtime

COPY --from=base ./app/out/ /app/

ENTRYPOINT [ "/app/can" ]
