on:
  push:
    branches: 
    - main
  schedule:
    - cron: "05 01 * * 2"
  workflow_dispatch:
jobs:
  build_with_azdo_repo:
    name: build go app with private dependency
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        env:
          AZDO_TOKEN_SECRET: ${{secrets.AZURE_ACCESS_TOKEN}}
        run: docker build --build-arg AZDO_ACCESS_TOKEN="${AZDO_TOKEN_SECRET}" .
